<?php
// Automatically Generated by TestLink Installer - Thu, 30 Dec 21 04:03:54 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'bgmfewjrcojeso');
define('DB_PASS', '0f0189c406abe68c275c79e31474a908b16db701fa7f9c299eb158fa069c3399');
define('DB_HOST', 'ec2-34-230-133-163.compute-1.amazonaws.com');
define('DB_NAME', 'd67r68imrk44ph');
define('DB_TABLE_PREFIX', '');
