<?php
// Automatically Generated by TestLink Installer - Thu, 30 Dec 21 04:03:54 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'admin');
define('DB_PASS', 'admin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'kiemthuphanmem');
define('DB_TABLE_PREFIX', '');
